language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
cache: bundler
script:
  - git fetch --tags
  - CI=true bundle exec rake
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rpm
  - gem install bundler -v 1.17.3
